---
output: 
  rmarkdown::html_document:
    theme: lumen
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
    storyboard: true
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## JMM 2019 
# Teaching Statistics Using R and RStudio {.tabset .tabset-fade .tabset-pills}

## Logistics

### This document is located at http://rpruim.github.io/JMM2019/

* We will update it throughout the week (and perhaps for a short time after).
* Bookmore the page so you can get back to it as needed.

### Wifi

  * network: Hiltonmtg
  * password: Stat2019
  
### Presenters/Organizers: 

* Randall Pruim (Calvin College)
* Shonda Kuiper (Grinnel College)

With special thanks to our "shoulder surfers": 

* Joyce Chew (Calvin College)
* Tracey Ramirez (Cal State Monterey Bay)
 

  
### Feedback 

 * We've created a [**Google doc**](https://docs.google.com/document/d/18JhF4eUSzLxiB2jZ_HAh8LJ_w0DQladCWP50O51VUnA/edit?usp=sharing) where you can leave feedback, ask questions, etc.

 * MAA has a [survey they would like you fill out](https://www.surveymonkey.com/r/5DF6YZP).

## Minicourse #2: <br>Start Teaching Statistics with R and RStudio

### Day 1: The Less Volume, More Creativity approach

#### Goals for the day

* Consider what "Less Volume, More Creativity" looks like in your own
courses

* Learn how to create (multivariate!) graphical and numerical summaries
in R

* Login to <https://rstudio.cloud>

#### Welcome

  * [Welcome Slides](welcome/JMM2019-welcome.html)

#### Less Volume, More Creativity

  * Slides
      * [[HTML]](less-volume/less-volume-slides.html)
      * [[Rmd]](less-volume/less-volume-slides.Rmd)
  
  * Tutorial 
      * [at rsconnect.calvin.edu](http://rsconnect.calvin.edu/less-volume/jmm2019)
      * [at shinyapps.io](https://rpruim.shinyapps.io/Less-Volume-JMM2019/)
      * [Google presentation with example plots](https://docs.google.com/presentation/d/11w4jK-PLc_v7Sm0gNcj5mAyHA8uyDWU7VTlYBjN9oks/edit?usp=sharing).

#### rstudio.cloud

[rstudio.cloud](https://rstudio.cloud) provides access to an online version of RStudio.

* Free version has some limitations, but is enough to get you started
    
* Create and account at <https://login.rstudio.cloud/login>
    
* Click on [this project link](https://rstudio.cloud/project/172687) to get started.
    
    * Note: It can take a few minutes to create a new project.  Be patient.
        
    * Once you are there, trying creating a plot by typing a command in the 
        "console".
        
    * If you want to save your work, be sure to save a copy.
        
    * We'll learn more about how to use rstudio.cloud tomorrow.
        
       
#### Additional Resources
 
  * [mosaic cheat sheet](https://github.com/mlaviolet/Mosaic-cheatsheets/raw/master/mosaic-cheatsheet-gf.pdf) 
  
  * In case you want to learn more about how to produce plots, here are some
  additional tutorials
  
    * Refining ggformula plots: 
        * [at rsconnect.calvin.edu](http://rsconnect.calvin.edu/ggformula/refining/)
        * [at shinyapps.io](https://rpruim.shinyapps.io/Refining_ggformula/)
  
    * Graphs with ggformula: <http://shiny.grinnell.edu/Tutorials/GraphsWithggformula/>
    
### Day 2: R Markdown for Instructors and Students


#### Goals for the day

* See the importance of a reproducible workflow.

* Learn how students and instructors can make use of RMarkdown to create
documents and webpages that include text, R code, R output, and graphics.

#### Before we start

**Option 1:**
Create an [rstudio.cloud](https://rstudio.cloud) account.
Once you have an Rstudio.cloud account, click on this link to open our Intro to R Markdown project: <https://rstudio.cloud/project/170774> .

* Note: It can take a few minutes to open or create a new project.  Be patient.
* If you want to save your work, be sure to save a copy.
   
**Option 2:**
Install R and Rstudio onto your desktop computer
and download these files:

* [IntroToRMarkdown/IntroductionToRMD_P1.Rmd](IntroToRMarkdown/IntroductionToRMD_P1.Rmd)
* [IntroToRMarkdown/IntroductionToRMD_P2.Rmd](IntroToRMarkdown/IntroductionToRMD_P2.Rmd)
* [Coffee.csv](IntroToRMarkdown/data/Coffee.csv)
* [Weather.csv](IntroToRMarkdown/data/Weather.csv)
* [CoffeeTruck.csv](IntroToRMarkdown/data/CoffeeTruck.csv)
* [CoffeeTruck2.csv](IntroToRMarkdown/data/CoffeeTruck2.csv)
* [CoffeeTruckInteractions.csv](IntroToRMarkdown/data/CoffeeTruckInteractoins.csv)


#### Additional Resources

 * [Reprodicible Research and R, Part 1](http://rpubs.com/skuiper/reproducibility1)
 * [Reprodicible Research and R, Part 2](http://rpubs.com/skuiper/reproducibility2)
 * [R Markdown Cheet Sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)  
 * [Prezi by Nick Horton](https://prezi.com/vq6l5yqpnqma/intro-to-r-markdown-cvc-2015/)
 * Rstudio.cloud project, Introduction to R Markdown: <https://rstudio.cloud/project/170774>
     * There are two Rmd files, make sure you complete the first before attempting part 2.
 * The [Stat2labs](http://web.grinnell.edu/individuals/kuipers/stat2labs/stat2labs/index.html) website includes [R tutorials](http://web.grinnell.edu/individuals/kuipers/stat2labs/stat2labs/RTutorials.html), [data visualizations](http://web.grinnell.edu/individuals/kuipers/stat2labs/NYPD.html), and [base-based educational activities](http://web.grinnell.edu/individuals/kuipers/stat2labs/Tangrams.html).

## Minicourse #12: <br>Keep Teaching Statistics with R and RStudio

### [Welcome](welcome/JMM2018-welcome2.html)

### Day 1: Data Wrangling with the tidyverse

#### Goals for the day

* Learn what **tidy data** is and why it is a useful concept
* Learn how to use basic components of `dplyr` toolkit to transform data


#### Resources

 * Intro to Data Wrangling Tutorial: 
    * <http://rsconnect.calvin.edu/wrangling-jmm2019>
    * <https://rpruim.shinyapps.io/wrangling-jmm2019>
    * [Rmd file](wrangling/intro/wrangling-jmm2019-Rmd.txt)
    
 * TB Case Study Tutorial: 
    * <http://rsconnect.calvin.edu/tidy-tb/>
    * <https://rpruim.shinyapps.io/tidydata-TB-tutorial/>
    * [Rmd file](wrangling/tb/tidydata-TB-tutorial-Rmd.txt)

### Day 2: Teaching Modeling with R

#### Goals for the day

#### Resources

* [Teaching Statistics with R](http://rpubs.com/skuiper/TeachStats1)
* An Rstudio.cloud project on creating maps <https://rstudio.cloud/spaces/8645/join?access_code=EU8AYhXB7vmNhHEToFUJLr9Fc6%2Fznnn%2Bb%2FdsBi%2Bo>
* Student activities, apps, datasets and code for the NYPD stop and frisk data: <http://web.grinnell.edu/individuals/kuipers/stat2labs/NYPD.html>
* Multiple tutorials and projects (case studies) on using R: <http://web.grinnell.edu/individuals/kuipers/stat2labs/RTutorials.html>  These include tidy data, visualizations, working with text files, working with dates and times, and making maps.


## Additional Resources and Information

<!-- ## R Studio Server -->

<!-- You are welcome to use an account on Calvin's RStudio server using the username and password  -->
<!-- provided.  Here's the link to get there. -->

<!--   * [rstudio.calvin.edu](http://rstudio.calvin.edu) -->

<!-- These accounts will likely be recycled in May or June, 2018. -->

### Websites for some packages we used

* [mosaic](https://projectmosaic.github.io/mosaic/)
* [ggformula](https://projectmosaic.github.io/ggformula/)

### Cheat Sheets

R Studio is assembling a number of useful cheat sheets at [www.rstudio.com/resources/cheatsheets/](https://www.rstudio.com/resources/cheatsheets/).  Among many others, are these

* [mosaic cheat sheet](https://github.com/mlaviolet/Mosaic-cheatsheets/raw/master/mosaic-cheatsheet-gf.pdf) 

* [RMarkdown cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)

* [Data Transformation cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)

* [RStudio cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)



### StatPREP

URL: <http://statprep.org/>

#### Regional Workshops
StatPREP will host four regional workshops in summer 2019 focused on helping
faculty learn to teach modern methods of data analytics in introductory
statistics courses. 

These workshops are open to any faculty member teaching post-secondary intro
stats over the next academic year. There is no registration fee for the workshop
and all workshop expenses are covered through support from the National Science
Foundation. Funds up to $100 are available for each participant to offset local
travel expenses.

* University of Hartford, Hartford, CT, May 31-June 1, 2019
* Howard Community College, greater DMV area, Washington, D.C, June 7-8, 2019
* Tarrant County College, Fort Worth, TX, June 14-15, 2019
* Highline College, Seattle/Tacoma, WA, June 21-22, 2019

#### Project Summary

StatPREP will foster the widespread use of data-centered methods and pedagogies
in introductory statistics courses. This will in turn enhance the preparation of
students to meet the demands of a data-driven workplace and to use the newly
available resources in our data-centric world. StatPREP will work directly with
college-level instructors, both online and in community-based workshops, to
develop the understanding and skills needed to work and teach with modern data.

StatPREP will initiate community transformation focused on modernizing undergraduate statistics education. This project will offer an extended professional development program for mathematics faculty, particularly at two-year institutions, who teach introductory statistics, it will establish regional communities of practice to support these instructors, and it will provide them a national online support network with statistics education experts. This project also contributes to the goal to “improve STEM learning and learning environments by investigating the effectiveness of this professional development model as a catalyst for community transformation. The combined resources and reach of the MAA, ASA, and AMATYC will ensure the sustainability of StatPREP and the availability of this program to the largest possible audience.


### rstudio.cloud

You (and your students) can set up accounts with <https://rstudio.cloud/>.
This is the easiest way to get going with R since no one needs to install or 
pay for anything.

This online version of RStudio is a new service and still under development.
Currently it is free.  Eventually there may be both free and paid plans.


### Running R Locally

You are welcome to work in your own local copy of R and RStudio if you prefer.  This will work best if you have a recent versions 

  * [R](http://cran.r-project.org)
  * [RStudio](http://rstudio.com)
  * the [`mosaic`](https://github.com/ProjectMOSAIC/mosaic) package and its dependencies
  * the [`ggformula`](https://github.com/ProjectMOSAIC/mosaic) package and its dependencies
  * the [`tidyverse`](https://github.com/tidyverse/tidyverse) package and its dependencies
  
Packages can be installed or updated using the Packages tab in RStudio.


### Setting up your own RStudio Server  

 * If you ask, RStudio will provide you with the professional server for free for qualifying academic purposes.  Contact them for details to see if you qualify.
 
 * If you want to serve tutorials, you will also need to set up RStudio Connect (and maybe a shiny server).  These aren't any harder than setting up RStudio Server, but they are separate software installs.
 
 * RStudio has lots of documentation about how to install and configure. For example, here is the [RStudio Server Pro admin guide](http://docs.rstudio.com/ide/server-pro/)
 
 * Here's a [blog post](https://www.r-bloggers.com/how-to-get-your-very-own-rstudio-server-and-shiny-server-with-digitalocean/) discussing how to do this with Digital Ocean.

 * Here's a [blog post](http://amunategui.github.io/EC2-RStudioServer/) about doing this with AWS.
 